const state={metrics:[['Incidenten',0],['Intelligence',0],['Kritieke CVE’s',0],['Open cases',0]],connectors:[],feed:[],vulnerabilities:[],iocs:[]};
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function setView(id){document.querySelectorAll('.view').forEach(v=>v.classList.toggle('active',v.id===id));document.querySelectorAll('nav button').forEach(b=>b.classList.toggle('active',b.dataset.view===id));document.querySelector('.sidebar').classList.remove('open')}
document.querySelectorAll('nav button').forEach(b=>b.addEventListener('click',()=>setView(b.dataset.view)));
document.querySelector('#menu').addEventListener('click',()=>document.querySelector('.sidebar').classList.toggle('open'));
document.querySelector('#theme').addEventListener('click',()=>{const h=document.documentElement;h.dataset.theme=h.dataset.theme==='dark'?'light':'dark';localStorage.setItem('dtmo-theme',h.dataset.theme)});
document.documentElement.dataset.theme=localStorage.getItem('dtmo-theme')||'light';
async function loadJson(path,fallback){try{const r=await fetch(path,{headers:{Accept:'application/json'}});if(!r.ok)throw new Error(r.status);return await r.json()}catch{return fallback}}
function render(){document.querySelector('#metrics').innerHTML=state.metrics.map(([k,v])=>`<div class="metric"><small>${esc(k)}</small><strong>${esc(v)}</strong></div>`).join('');document.querySelector('#connectors').innerHTML=state.connectors.length?state.connectors.map(c=>`<p><strong>${esc(c.id)}</strong> — ${c.healthy?'healthy':'degraded'}</p>`).join(''):'<p>Geen connectorstatus geladen.</p>';document.querySelector('#priorities').innerHTML=state.vulnerabilities.slice(0,5).map(v=>`<p><strong>${esc(v.cve_id)}</strong> — ${esc(v.vendor)} ${esc(v.product)}</p>`).join('')||'<p>Geen prioriteiten geladen.</p>';document.querySelector('#feed').innerHTML=state.feed.map(i=>`<article class="card"><small>${esc(i.source_id)}</small><h3>${esc(i.title)}</h3><p>${esc(i.summary)}</p></article>`).join('');document.querySelector('#vulnRows').innerHTML=state.vulnerabilities.map(v=>`<tr><td>${esc(v.cve_id)}</td><td>${esc(v.vendor)}</td><td>${esc(v.product)}</td><td>${esc(v.cvss)}</td><td>${v.kev?'Ja':'Nee'}</td><td>${esc(v.education_relevance)}</td></tr>`).join('');document.querySelector('#iocRows').innerHTML=state.iocs.map(i=>`<article class="card"><small>${esc(i.indicator_type)}</small><h3><code>${esc(i.value)}</code></h3><p>Confidence ${esc(i.confidence)} · ${esc(i.source)}</p></article>`).join('');const nodes=[['CVE',12,20],['Product',42,43],['Vendor',72,20],['Actor',20,73],['Malware',55,78]];document.querySelector('#graphCanvas').innerHTML=nodes.map(([n,x,y])=>`<span class="node" style="left:${x}%;top:${y}%">${n}</span>`).join('')}
async function init(){const summary=await loadJson('/api/v1/dashboard/summary',{});state.metrics=[['Incidenten',summary.incidents||0],['Intelligence',summary.intelligence||0],['Kritieke CVE’s',summary.critical_vulnerabilities||0],['Open cases',summary.open_cases||0]];state.connectors=await loadJson('/connectors',[]);state.feed=await loadJson('/api/v1/intelligence?limit=50',[]);state.vulnerabilities=await loadJson('/api/v1/vulnerabilities?limit=100',[]);state.iocs=await loadJson('/api/v1/iocs?limit=100',[]);render()}
document.querySelector('#search').addEventListener('keydown',e=>{if(e.key==='Enter')window.location.hash=`search=${encodeURIComponent(e.target.value)}`});init();