from __future__ import annotations

from typing import Annotated

from fastapi import APIRouter, Depends, Query
from fastapi.responses import HTMLResponse
from sqlalchemy import select
from sqlalchemy.ext.asyncio import AsyncSession

from dtmo.api.routes import get_session
from dtmo.auth.dependencies import require_permission
from dtmo.auth.policy import Permission, Principal
from dtmo.persistence.models import IntelligenceItem

router = APIRouter()


def _enum_value(value: object) -> str:
    return str(getattr(value, "value", value))


@router.get("/api/v1/console/recent-intelligence")
async def recent_console_intelligence(
    principal: Annotated[Principal, Depends(require_permission(Permission.READ_INTELLIGENCE))],
    session: Annotated[AsyncSession, Depends(get_session)],
    limit: int = Query(default=20, ge=1, le=100),
) -> list[dict[str, object]]:
    """Return canonical recent intelligence independently of the OpenSearch read path."""
    del principal
    items = (
        await session.scalars(
            select(IntelligenceItem)
            .order_by(IntelligenceItem.discovered_at.desc())
            .limit(limit)
        )
    ).all()
    return [
        {
            "id": str(item.id),
            "source_id": item.source_id,
            "title": item.title,
            "summary": item.summary,
            "severity": _enum_value(item.severity),
            "confidence_score": item.confidence_score,
            "education_relevance": item.education_relevance,
            "review_status": item.review_status,
            "share_approved": item.share_approved,
            "canonical_url": item.canonical_url,
            "published_at": item.published_at.isoformat() if item.published_at else None,
            "discovered_at": item.discovered_at.isoformat(),
        }
        for item in items
    ]


_PAGE = r'''<!doctype html>
<html lang="nl">
<head>
<meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1">
<title>DTMO — Unified Console</title><link rel="stylesheet" href="/ui/design-system.css">
<style>
.shell{min-height:100vh;display:grid;grid-template-columns:250px minmax(0,1fr)}.side{position:sticky;top:0;height:100vh;padding:1.25rem;background:var(--surface);border-right:1px solid var(--line)}.side nav{display:grid;gap:.35rem;margin-top:1.4rem}.side button{width:100%;text-align:left}.main{min-width:0}.top{position:sticky;top:0;z-index:5;display:flex;justify-content:space-between;gap:1rem;align-items:center;padding:1rem 1.5rem;background:var(--bg);border-bottom:1px solid var(--line)}.view{display:none}.view.active{display:block}.grid{display:grid;grid-template-columns:repeat(auto-fit,minmax(280px,1fr));gap:1rem}.cards{display:grid;gap:.75rem}.card{border:1px solid var(--line);border-radius:12px;padding:1rem;background:var(--surface-2)}.actions{display:flex;gap:.5rem;flex-wrap:wrap;align-items:center}.button:disabled{opacity:.55;cursor:wait}.chart{display:flex;align-items:end;gap:.4rem;min-height:180px;padding:1rem 0}.chart-empty{display:flex;align-items:center;justify-content:center;width:100%;min-height:150px;padding:1rem;border:1px dashed var(--line);border-radius:10px;text-align:center}.bar-wrap{flex:1;text-align:center;min-width:42px}.bar{width:100%;background:currentColor;border-radius:6px 6px 0 0;opacity:.75}.bar-label{font-size:.72rem;overflow-wrap:anywhere}.metric strong{display:block;font-size:1.8rem}.status{min-height:1.5rem}.admin-grid{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:1rem}.admin-grid #rbac-administration{grid-column:1/-1}.admin-summary strong{display:block;font-size:1.6rem}.dev-context summary{cursor:pointer;font-weight:700}.dev-context[open] summary{margin-bottom:.75rem}.source-meta{display:grid;grid-template-columns:repeat(auto-fit,minmax(170px,1fr));gap:.35rem .75rem}.source-control{display:flex;gap:.5rem;align-items:center;flex-wrap:wrap;margin-top:.75rem}.source-control input[type=number]{width:8rem}.diagnostic{margin-top:.5rem;font-size:.9rem}.muted-code{font-family:ui-monospace,SFMono-Regular,Menlo,monospace;font-size:.82rem;overflow-wrap:anywhere}.overview-grid{display:grid;grid-template-columns:repeat(auto-fit,minmax(300px,1fr));gap:1rem;margin-top:1rem}.intel-list{display:grid;gap:.65rem}.intel-meta{display:flex;gap:.5rem;flex-wrap:wrap;font-size:.85rem}.empty-state{padding:1rem;border:1px dashed var(--line);border-radius:10px}.grafana-shell{margin-top:1.25rem}.grafana-tabs{display:flex;gap:.5rem;flex-wrap:wrap;margin-bottom:.75rem}.grafana-frame{display:none;width:100%;height:720px;border:1px solid var(--line);border-radius:12px;background:var(--surface-2)}.grafana-frame.active{display:block}.grafana-note{margin:.5rem 0 1rem}@media(max-width:900px){.admin-grid{grid-template-columns:1fr}}@media(max-width:800px){.shell{display:block}.side{position:relative;height:auto}.side nav{grid-template-columns:repeat(2,1fr)}.top{position:relative}.grafana-frame{height:560px}}
</style>
</head>
<body>
<a class="skip-link" href="#content">Ga naar hoofdinhoud</a>
<div class="shell"><aside class="side"><div class="brand"><div class="brand-mark">D</div><div><strong>DTMO</strong><span>Threat Operations</span></div></div><nav aria-label="Hoofdnavigatie">
<button type="button" class="button secondary" data-view="overview">Overzicht</button><button type="button" class="button secondary" data-view="intelligence">Intelligence</button><button type="button" class="button secondary" data-view="sources">Bronnen & catalogus</button><button type="button" class="button secondary" data-view="analytics">Visual analytics</button><button type="button" class="button secondary" data-view="administration">Administration</button><button type="button" class="button secondary" data-view="governance">Governance</button>
</nav></aside>
<div class="main"><header class="top"><div><p class="eyebrow">Dutch Threat Monitoring for Education</p><h1>Threat Operations Console</h1></div><div><span id="global-status" class="status-pill neutral" data-testid="global-status" role="status" aria-live="polite">Console laden…</span></div></header>
<main id="content" class="workspace">
<section class="view active" data-view-panel="overview"><div class="page-heading"><div><p class="eyebrow">Operational picture</p><h2>Overzicht</h2><p>Actuele intelligence-, bron- en connectorstatus vanuit de canonical DTMO-datalaag.</p></div><button type="button" class="button" id="refresh-all">Alles vernieuwen</button></div>
<div class="kpi-grid"><article class="kpi-card metric"><span>Intelligence</span><strong id="kpi-intel">—</strong><small>Canonical records</small></article><article class="kpi-card metric"><span>Nieuwe 24h</span><strong id="kpi-new">—</strong><small>Fresh intelligence</small></article><article class="kpi-card metric"><span>Gem. confidence</span><strong id="kpi-confidence">—</strong><small>Canonical intelligence</small></article><article class="kpi-card metric"><span>Catalogus</span><strong id="kpi-catalog">—</strong><small>Curated sources</small></article><article class="kpi-card metric"><span>Geregistreerd</span><strong id="kpi-registered">—</strong><small>Framework sources</small></article><article class="kpi-card metric"><span>Handmatig uitvoerbaar</span><strong id="kpi-runnable">—</strong><small>Sources ready now</small></article></div>
<div class="overview-grid"><article class="surface"><h3>Intelligence trend — 7 dagen</h3><div id="overview-trend-chart" class="chart"></div><div id="overview-trend-table"></div></article><article class="surface"><h3>Severity</h3><div id="overview-severity-chart" class="chart"></div><div id="overview-severity-table"></div></article><article class="surface"><h3>Connector health</h3><div id="overview-connector-chart" class="chart"></div><div id="overview-connector-table"></div></article></div>
<article class="surface"><div class="page-heading"><div><h3>Recente intelligence</h3><p>De laatste canonical records, onafhankelijk van OpenSearch.</p></div><button type="button" class="button secondary" data-view="intelligence">Open Intelligence</button></div><div id="overview-recent" class="intel-list" data-testid="overview-recent"></div></article></section>
<section class="view" data-view-panel="intelligence"><div class="page-heading"><div><p class="eyebrow">Analyse</p><h2>Intelligence</h2><p>Recente canonical intelligence is direct zichtbaar; vrije zoekopdrachten gebruiken de governed search API.</p></div><button type="button" id="refresh-intelligence" class="button secondary">Recente intelligence vernieuwen</button></div><article class="surface"><h3>Recent ingested</h3><div id="intel-recent-status" class="status" role="status"></div><div id="intel-recent" class="intel-list" data-testid="intel-recent"></div></article><article class="surface"><h3>Zoeken</h3><form id="intel-search" class="actions"><input id="intel-query" minlength="2" required placeholder="Zoek intelligence"><button class="button" type="submit">Zoeken</button></form><div id="intel-status" class="status" role="status"></div><div id="intel-results" class="cards"></div></article></section>
<section class="view" data-view-panel="sources"><div class="page-heading"><div><p class="eyebrow">Source operations</p><h2>Bronnen & catalogus</h2><p>Registreren, activeren, valideren, interval beheren en feeds laden vanuit één operatorflow.</p></div><div class="actions"><button type="button" id="bootstrap" class="button secondary">Frameworkbronnen registreren</button><button type="button" id="refresh-sources" class="button secondary">Vernieuwen</button></div></div><div id="source-status" class="status" role="status" data-testid="source-status"></div><div id="source-cards" class="cards" data-testid="source-cards"></div></section>
<section class="view" data-view-panel="analytics"><div class="page-heading"><div><p class="eyebrow">Visual intelligence</p><h2>Visual analytics</h2><p>Native DTMO-analytics tonen alleen meetbare data. Als er nog geen intelligence is, wordt dat expliciet als lege toestand weergegeven.</p></div></div><p class="eyebrow">Native console summary</p><div class="grid"><article class="surface"><h3>Severity distribution</h3><div id="severity-chart" class="chart"></div><div id="severity-table"></div></article><article class="surface"><h3>Source distribution</h3><div id="source-chart" class="chart"></div><div id="source-table"></div></article><article class="surface"><h3>Connector health</h3><div id="connector-chart" class="chart"></div><div id="connector-table"></div></article><article class="surface"><h3>Review status</h3><div id="review-chart" class="chart"></div><div id="review-table"></div></article></div><article class="surface grafana-shell"><h3>Advanced Grafana dashboards</h3><p class="muted grafana-note">Grafana blijft een afzonderlijk geauthenticeerde operations-view. De native analytics hierboven vormen de canonical productweergave.</p><div class="grafana-tabs" role="tablist" aria-label="Grafana dashboards"><button class="button secondary" type="button" data-grafana-tab="operations">Open Operations in Grafana</button><button class="button secondary" type="button" data-grafana-tab="intelligence">Open Intelligence in Grafana</button></div><iframe id="grafana-operations" class="grafana-frame" title="DTMO Operations dashboard" loading="lazy" referrerpolicy="same-origin"></iframe><iframe id="grafana-intelligence" class="grafana-frame" title="DTMO Intelligence dashboard" loading="lazy" referrerpolicy="same-origin"></iframe></article></section>
<section class="view" data-view-panel="administration"><div class="page-heading"><div><p class="eyebrow">Control plane</p><h2>Administration</h2><p>Beheer governed gebruikers en rollen vanuit één centrale werkruimte. Bronbeheer blijft bewust in Bronnen & catalogus.</p></div><button type="button" class="button secondary" data-view="sources">Open bronbeheer</button></div><div class="admin-grid"><article class="surface"><h3>Bronbeheer</h3><p>Bronregistratie en feeduitvoering worden op één plek beheerd om dubbele bediening te voorkomen.</p><div id="admin-sources" class="admin-summary"></div><button type="button" class="button secondary" data-view="sources">Naar Bronnen & catalogus</button></article><details class="surface dev-context" id="dev-identity-context"><summary>Technische sessiecontext (development)</summary><p class="muted">Alleen voor lokale ontwikkel- en testcontext. Productie-identiteit blijft extern beheerd.</p><label>Subject<input id="subject" value="admin-tester"></label><label>Rollen<input id="roles" value="admin"></label><label>API key<input id="api-key" type="password"></label><button type="button" id="save-identity" class="button secondary">Sessiecontext toepassen</button></details><article class="surface"><h3>Bevoegdheidsgrens</h3><p>Administration verleent geen review- of share approval-recht. Human review en externe share approval blijven afzonderlijke server-side bevoegdheden.</p></article></div></section>
<section class="view" data-view-panel="governance"><div class="page-heading"><div><p class="eyebrow">Governance</p><h2>Governance knowledge</h2><p>Frameworkdekking, repository-backed mappings en beslisgrenzen worden alleen getoond met expliciete provenance.</p></div></div><article class="surface"><p>Ingestie, dashboards en administration verlenen geen review- of share approval-recht. Human review en externe share approval blijven afzonderlijke bevoegdheden met separation of duties.</p></article></section>
</main></div></div>
<script>
const $=id=>document.getElementById(id),esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const ctx={subject:sessionStorage.getItem('dtmo.subject')||'admin-tester',roles:sessionStorage.getItem('dtmo.roles')||'admin',apiKey:sessionStorage.getItem('dtmo.apiKey')||''};
function closestTarget(event,selector){return event.target instanceof Element?event.target.closest(selector):null}
function requestId(){return globalThis.crypto?.randomUUID?.()||`dtmo-${Date.now()}-${Math.random().toString(16).slice(2)}`}
function headers(write=false,json=false){const h={'X-DTMO-Subject':ctx.subject,'X-DTMO-Roles':ctx.roles,'X-DTMO-API-Key':ctx.apiKey};if(write)h['X-Request-ID']=requestId();if(json)h['Content-Type']='application/json';return h}
async function api(url,opt={}){const r=await fetch(url,{...opt,headers:{...headers(Boolean(opt.method&&opt.method!=='GET'),Boolean(opt.body)),...(opt.headers||{})}});let b={};try{b=await r.json()}catch{}if(!r.ok)throw new Error(b.detail||b.reason||`HTTP ${r.status}`);return b}
function show(name){document.querySelectorAll('[data-view-panel]').forEach(x=>x.classList.toggle('active',x.dataset.viewPanel===name));document.querySelectorAll('nav [data-view]').forEach(x=>x.classList.toggle('secondary',x.dataset.view!==name));location.hash=name}
document.addEventListener('click',e=>{const b=closestTarget(e,'[data-view]');if(b){e.preventDefault();show(b.dataset.view)}});
function initGrafana(){const base='/grafana';const ops=$('grafana-operations'),intel=$('grafana-intelligence');if(ops&&!ops.src)ops.src=`${base}/d/dtmo-operations/dtmo-operations?orgId=1&kiosk`;if(intel&&!intel.src)intel.src=`${base}/d/dtmo-intelligence/dtmo-intelligence?orgId=1&kiosk`}
function showGrafana(name){initGrafana();document.querySelectorAll('.grafana-frame').forEach(frame=>frame.classList.toggle('active',frame.id===`grafana-${name}`));document.querySelectorAll('[data-grafana-tab]').forEach(button=>button.classList.toggle('secondary',button.dataset.grafanaTab!==name))}
document.addEventListener('click',e=>{const tab=closestTarget(e,'[data-grafana-tab]');if(tab){e.preventDefault();showGrafana(tab.dataset.grafanaTab)}});
function bars(target,tableTarget,obj,emptyMessage='Nog geen meetbare data.'){const entries=Object.entries(obj||{}).map(([k,v])=>[k,Number(v)||0]);const total=entries.reduce((sum,[,v])=>sum+Math.max(0,v),0);if(!entries.length||total<=0){$(target).innerHTML=`<div class="chart-empty"><div><strong>Geen data om te visualiseren</strong><p class="muted">${esc(emptyMessage)}</p></div></div>`;$(tableTarget).innerHTML='';return false}const max=Math.max(1,...entries.map(([,v])=>v));$(target).innerHTML=entries.map(([k,v])=>`<div class="bar-wrap"><div class="bar" style="height:${v>0?Math.max(8,Math.min(160,(v/max)*160)):2}px" title="${esc(k)}: ${esc(v)}"></div><div class="bar-label">${esc(k)}</div></div>`).join('');$(tableTarget).innerHTML=`<table><thead><tr><th>Type</th><th>Aantal</th></tr></thead><tbody>${entries.map(([k,v])=>`<tr><td>${esc(k)}</td><td>${esc(v)}</td></tr>`).join('')}</tbody></table>`;return true}
async function loadDashboard(){try{const d=await api('/api/v1/dashboards/summary');$('kpi-intel').textContent=d.total_intelligence??0;$('kpi-new').textContent=d.new_last_24h??0;$('kpi-confidence').textContent=`${Number(d.average_confidence??0).toFixed(1)}%`;bars('overview-trend-chart','overview-trend-table',d.intelligence_trend_7d||{},'Nog geen intelligence in de afgelopen 7 dagen.');bars('overview-severity-chart','overview-severity-table',d.severity||{},'Nog geen intelligence met severity-classificatie.');bars('overview-connector-chart','overview-connector-table',d.connector_health||{},'Nog geen connectorstatus beschikbaar.');bars('severity-chart','severity-table',d.severity||{},'Nog geen intelligence met severity-classificatie.');bars('source-chart','source-table',d.sources||{},'Nog geen intelligencebronnen met ingested records.');bars('connector-chart','connector-table',d.connector_health||{},'Nog geen connectorstatus beschikbaar.');bars('review-chart','review-table',d.review_status||{},'Nog geen intelligence in een reviewstatus.');return {ok:true,data:d}}catch(e){return {ok:false,error:e}}}
function sourceCard(c,s,r){const built=c.execution_status==='supported-built-in',supported=c.execution_status==='supported'||built,registered=built||Boolean(s?.registered)||Boolean(r),enabled=built?Boolean(s?.enabled):Boolean(r?.enabled),manual=Boolean(s?.manual_run_available),run=manual&&(built||enabled);let why=!supported?'Research reference':built?(manual?'Built-in · handmatige run beschikbaar':'Built-in · handmatige run geblokkeerd'):!registered?'Nog niet geregistreerd':!enabled?'Geregistreerd · uitgeschakeld':'Operationeel';let controls='';if(built){controls=run?`<button type="button" class="button" data-run="${esc(c.id)}" data-built="true">Feed nu laden</button>`:'<span class="muted">Handmatige run niet beschikbaar in deze omgeving.</span>'}else if(!supported){controls='<span class="muted">Niet uitvoerbaar; research/reference bron.</span>'}else if(!registered){controls='<span class="muted">Gebruik “Frameworkbronnen registreren” om deze adapter te registreren.</span>'}else{controls=`<label><input type="checkbox" data-enabled="${esc(c.id)}" ${enabled?'checked':''}> Actief</label><label>Interval <input type="number" min="60" max="86400" step="60" data-interval="${esc(c.id)}" value="${esc(r?.interval_seconds||s?.interval_seconds||c.recommended_interval_seconds||3600)}"> sec</label><button type="button" class="button secondary" data-save="${esc(c.id)}">Opslaan</button><button type="button" class="button secondary" data-validate="${esc(c.id)}">Valideren</button>${run?`<button type="button" class="button" data-run="${esc(c.id)}" data-built="false">Feed nu laden</button>`:''}`};return `<article class="card" data-source-card="${esc(c.id)}"><div><strong>${esc(c.name)}</strong> <span class="status-pill ${run?'good':'neutral'}">${esc(why)}</span></div><div class="source-meta"><span>${esc(c.category)}</span><span>${esc(c.reliability)}</span><span class="muted-code">${esc(c.execution_profile)}</span><span>${esc(c.execution_status)}</span><span>Health: ${esc(s?.health_status||'unknown')}</span><span>Laatste succes: ${esc(s?.last_success_at||'—')}</span></div><p class="muted-code">${esc(c.endpoint_url)}</p><div class="source-control">${controls}</div><div class="diagnostic" data-result="${esc(c.id)}" role="status"></div></article>`}
async function loadSources(){try{const [catalog,status,registered]=await Promise.all([api('/api/v1/admin/sources/catalog'),api('/api/v1/source-center/status'),api('/api/v1/admin/sources')]);const sm=Object.fromEntries(status.map(x=>[x.id,x])),rm=Object.fromEntries(registered.map(x=>[x.id,x]));$('kpi-catalog').textContent=catalog.length;$('kpi-registered').textContent=status.filter(x=>x.registered).length;$('kpi-runnable').textContent=status.filter(x=>x.manual_run_available).length;$('source-cards').innerHTML=catalog.length?catalog.map(c=>sourceCard(c,sm[c.id],rm[c.id])).join(''):'<div class="empty-state">Geen catalogusbronnen beschikbaar.</div>';const admin=$('admin-sources');if(admin)admin.innerHTML=`<strong>${registered.length}</strong><span>geregistreerde frameworkbron${registered.length===1?'':'nen'} · ${status.filter(x=>x.manual_run_available).length} handmatig uitvoerbaar</span>`;$('source-status').textContent=`${catalog.length} catalogusbronnen; ${status.filter(x=>x.registered).length} beschikbaar/geregistreerd; ${status.filter(x=>x.manual_run_available).length} handmatig uitvoerbaar.`;return {ok:true,catalog,status,registered}}catch(e){$('source-status').textContent='Bronnen laden mislukt: '+e.message;return {ok:false,error:e}}}
async function bootstrap(){try{$('source-status').textContent='Frameworkbronnen registreren…';const d=await api('/api/v1/admin/sources/catalog/bootstrap',{method:'POST'});$('source-status').textContent=`${d.length} frameworkbronnen geregistreerd of reeds aanwezig.`;await loadSources()}catch(e){$('source-status').textContent='Registratie mislukt: '+e.message}}
async function patchSource(id,body){return api(`/api/v1/admin/sources/${encodeURIComponent(id)}`,{method:'PATCH',body:JSON.stringify(body)})}
function resultElement(id){return document.querySelector(`[data-result="${CSS.escape(id)}"]`)}
async function saveSource(id){const enabled=document.querySelector(`[data-enabled="${CSS.escape(id)}"]`)?.checked,interval=Number(document.querySelector(`[data-interval="${CSS.escape(id)}"]`)?.value);const el=resultElement(id);try{if(el)el.textContent='Instellingen opslaan…';await patchSource(id,{enabled,interval_seconds:interval});await loadSources();const current=resultElement(id);if(current)current.textContent='Broninstellingen opgeslagen.'}catch(e){const current=resultElement(id)||el;if(current)current.textContent='Opslaan mislukt: '+e.message}}
async function validateSource(id){const el=resultElement(id);try{if(el)el.textContent='Validatie uitvoeren…';const d=await api(`/api/v1/admin/sources/${encodeURIComponent(id)}/validate`,{method:'POST'});if(el)el.textContent=d.valid?`Valid: ${d.execution}. ${d.note||''}`:`Ongeldig: ${d.reason||'onbekende reden'}`}catch(e){if(el)el.textContent='Validatie mislukt: '+e.message}}
async function run(id,built){const el=resultElement(id);try{if(el)el.textContent='Feed laden en verwerken…';const url=built?`/connectors/${encodeURIComponent(id)}/run`:`/api/v1/admin/sources/${encodeURIComponent(id)}/run`;const d=await api(url,{method:'POST'});const message=`${d.status}: ${d.records??0} records, ${d.inserted??0} inserted, ${d.indexed??0} indexed. Publication gate: ${d.publication_gate||'human-approval-required'}`;await refreshAll({preserveButton:true});const current=resultElement(id);if(current)current.textContent=message;$('source-status').textContent=`${id}: ${d.status}; ${d.records??0} records, ${d.inserted??0} inserted, ${d.indexed??0} indexed.`}catch(e){const current=resultElement(id)||el;if(current)current.textContent='Run mislukt/geblokkeerd: '+e.message}}
function intelCard(x){return `<article class="card"><div class="intel-meta"><span class="status-pill neutral">${esc(x.severity||'informational')}</span><span>${esc(x.source_id||'onbekende bron')}</span><span>${esc(x.discovered_at?new Date(x.discovered_at).toLocaleString():'')}</span></div><strong>${esc(x.title||x.id)}</strong><p>${esc(x.summary||x.description||'')}</p>${x.canonical_url?`<a href="${esc(x.canonical_url)}" rel="noopener noreferrer">Bron openen</a>`:''}</article>`}
async function loadRecentIntelligence(){try{const rows=await api('/api/v1/console/recent-intelligence?limit=20');const html=rows.length?rows.map(intelCard).join(''):`<div class="empty-state"><strong>Nog geen intelligence ingested.</strong><p>Open Bronnen & catalogus, registreer/activeer een bron en kies “Feed nu laden”.</p><button type="button" class="button secondary" data-view="sources">Open bronnen</button></div>`;$('intel-recent').innerHTML=html;$('overview-recent').innerHTML=rows.length?rows.slice(0,5).map(intelCard).join(''):html;$('intel-recent-status').textContent=rows.length?`${rows.length} recente records geladen.`:'Nog geen canonical intelligence beschikbaar.';return {ok:true,rows}}catch(e){$('intel-recent-status').textContent='Recente intelligence laden mislukt: '+e.message;return {ok:false,error:e,rows:[]}}}
async function refreshAll(options={}){const button=$('refresh-all'),preserveButton=Boolean(options.preserveButton);if(button&&!preserveButton){button.disabled=true;button.textContent='Vernieuwen…'}$('global-status').textContent=options.initial?'Console laden…':'Gegevens vernieuwen…';try{const [sources,dashboard,recent]=await Promise.all([loadSources(),loadDashboard(),loadRecentIntelligence()]);const failed=[sources,dashboard,recent].filter(result=>!result.ok);if(failed.length){$('global-status').textContent=`Vernieuwen deels mislukt (${failed.length})`;return {ok:false,sources,dashboard,recent}}const total=Number(dashboard.data?.total_intelligence||0),recentCount=recent.rows.length;if(total===0&&recentCount===0){$('global-status').textContent='Geen intelligence data · bronstatus geladen'}else{$('global-status').textContent=`Bijgewerkt · ${total} intelligence record${total===1?'':'s'}`}return {ok:true,sources,dashboard,recent}}finally{if(button&&!preserveButton){button.disabled=false;button.textContent='Alles vernieuwen'}}}
$('source-cards')?.addEventListener('click',e=>{const r=closestTarget(e,'[data-run]'),s=closestTarget(e,'[data-save]'),v=closestTarget(e,'[data-validate]');if(r)void run(r.dataset.run,r.dataset.built==='true');else if(s)void saveSource(s.dataset.save);else if(v)void validateSource(v.dataset.validate)});
$('bootstrap')?.addEventListener('click',()=>void bootstrap());$('refresh-sources')?.addEventListener('click',()=>void loadSources());$('refresh-intelligence')?.addEventListener('click',()=>void loadRecentIntelligence());$('refresh-all')?.addEventListener('click',()=>void refreshAll());
$('save-identity')?.addEventListener('click',()=>{ctx.subject=$('subject').value.trim();ctx.roles=$('roles').value.trim();ctx.apiKey=$('api-key').value;sessionStorage.setItem('dtmo.subject',ctx.subject);sessionStorage.setItem('dtmo.roles',ctx.roles);sessionStorage.setItem('dtmo.apiKey',ctx.apiKey);void refreshAll()});
$('intel-search')?.addEventListener('submit',async e=>{e.preventDefault();const q=$('intel-query').value.trim();$('intel-status').textContent='Zoeken…';try{const d=await api(`/api/v1/intelligence/search?q=${encodeURIComponent(q)}`);const rows=Array.isArray(d)?d:(d.items||d.results||[]);$('intel-results').innerHTML=rows.length?rows.map(intelCard).join(''):'<div class="empty-state">Geen zoekresultaten.</div>';$('intel-status').textContent=`${rows.length} resultaten.`}catch(err){$('intel-status').textContent='Zoeken mislukt: '+err.message}});
window.addEventListener('error',event=>{if($('global-status'))$('global-status').textContent=`Interfacefout: ${event.message||'onbekende fout'}`});
window.addEventListener('unhandledrejection',event=>{if($('global-status'))$('global-status').textContent=`Interfacefout: ${event.reason?.message||event.reason||'onbekende fout'}`});
const initial=location.hash.slice(1);if(initial&&document.querySelector(`[data-view-panel="${CSS.escape(initial)}"]`))show(initial);else show('overview');$('subject').value=ctx.subject;$('roles').value=ctx.roles;void refreshAll({initial:true});
</script></body></html>'''


@router.get("/", response_class=HTMLResponse)
def unified_console_root() -> HTMLResponse:
    return HTMLResponse(_PAGE)


@router.get("/ui/console", response_class=HTMLResponse)
def unified_console() -> HTMLResponse:
    return HTMLResponse(_PAGE)
