from __future__ import annotations

from fastapi import APIRouter
from fastapi.responses import HTMLResponse

router = APIRouter()

_PAGE = r'''<!doctype html>
<html lang="nl">
<head>
<meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1">
<title>DTMO — Unified Console</title><link rel="stylesheet" href="/ui/design-system.css">
<style>
.shell{min-height:100vh;display:grid;grid-template-columns:250px minmax(0,1fr)}.side{position:sticky;top:0;height:100vh;padding:1.25rem;background:var(--surface);border-right:1px solid var(--line)}.side nav{display:grid;gap:.35rem;margin-top:1.4rem}.side button{width:100%;text-align:left}.main{min-width:0}.top{position:sticky;top:0;z-index:5;display:flex;justify-content:space-between;gap:1rem;align-items:center;padding:1rem 1.5rem;background:var(--bg);border-bottom:1px solid var(--line)}.view{display:none}.view.active{display:block}.grid{display:grid;grid-template-columns:repeat(auto-fit,minmax(280px,1fr));gap:1rem}.cards{display:grid;gap:.75rem}.card{border:1px solid var(--line);border-radius:12px;padding:1rem;background:var(--surface-2)}.actions{display:flex;gap:.5rem;flex-wrap:wrap;align-items:center}.chart{display:flex;align-items:end;gap:.4rem;height:180px;padding:1rem 0}.bar{min-width:42px;flex:1;background:currentColor;border-radius:6px 6px 0 0;opacity:.75}.bar-label{font-size:.72rem;overflow-wrap:anywhere}.metric strong{display:block;font-size:1.8rem}.status{min-height:1.5rem}.admin-grid{display:grid;grid-template-columns:repeat(auto-fit,minmax(260px,1fr));gap:1rem}.source-meta{display:grid;grid-template-columns:repeat(auto-fit,minmax(170px,1fr));gap:.35rem .75rem}.source-control{display:flex;gap:.5rem;align-items:center;flex-wrap:wrap;margin-top:.75rem}.source-control input[type=number]{width:8rem}.diagnostic{margin-top:.5rem;font-size:.9rem}.good-text{font-weight:700}.muted-code{font-family:ui-monospace,SFMono-Regular,Menlo,monospace;font-size:.82rem;overflow-wrap:anywhere}.grafana-shell{margin-bottom:1rem}.grafana-tabs{display:flex;gap:.5rem;flex-wrap:wrap;margin-bottom:.75rem}.grafana-frame{display:none;width:100%;height:720px;border:1px solid var(--line);border-radius:12px;background:var(--surface-2)}.grafana-frame.active{display:block}.grafana-note{margin:.5rem 0 1rem}.fallback-heading{margin-top:1.5rem}@media(max-width:800px){.shell{display:block}.side{position:relative;height:auto}.side nav{grid-template-columns:repeat(2,1fr)}.top{position:relative}.grafana-frame{height:560px}}
</style>
</head>
<body>
<a class="skip-link" href="#content">Ga naar hoofdinhoud</a>
<div class="shell"><aside class="side"><div class="brand"><div class="brand-mark">D</div><div><strong>DTMO</strong><span>Unified Console</span></div></div><nav aria-label="Hoofdnavigatie">
<button class="button secondary" data-view="overview">Overzicht</button><button class="button secondary" data-view="intelligence">Intelligence</button><button class="button secondary" data-view="sources">Bronnen & catalogus</button><button class="button secondary" data-view="analytics">Visual analytics</button><button class="button secondary" data-view="administration">Administration</button><button class="button secondary" data-view="governance">Governance</button>
</nav><p class="muted">Eén applicatieshell. Legacy `/ui/*`-views blijven alleen compatibiliteitspaden.</p></aside>
<div class="main"><header class="top"><div><p class="eyebrow">Dutch Threat Monitoring for Education</p><h1>Threat Operations Console</h1></div><div><span id="global-status" class="status-pill neutral">Niet geladen</span></div></header>
<main id="content" class="workspace">
<section class="view active" data-view-panel="overview"><div class="page-heading"><div><p class="eyebrow">Unified workspace</p><h2>Overzicht</h2><p>Operationeel, intelligence- en governancebeeld vanuit één console.</p></div><button class="button" id="refresh-all">Alles vernieuwen</button></div><div class="kpi-grid"><article class="kpi-card metric"><span>Intelligence</span><strong id="kpi-intel">—</strong><small>Canonical records</small></article><article class="kpi-card metric"><span>Nieuwe 24h</span><strong id="kpi-new">—</strong><small>Fresh intelligence</small></article><article class="kpi-card metric"><span>Catalogus</span><strong id="kpi-catalog">—</strong><small>Curated sources</small></article><article class="kpi-card metric"><span>Operationeel</span><strong id="kpi-runnable">—</strong><small>Registered executable sources</small></article></div></section>
<section class="view" data-view-panel="intelligence"><div class="page-heading"><div><p class="eyebrow">Analyse</p><h2>Intelligence</h2><p>Gebruik de bestaande governed intelligence API binnen dezelfde console.</p></div></div><article class="surface"><form id="intel-search" class="actions"><input id="intel-query" minlength="2" required placeholder="Zoek intelligence"><button class="button" type="submit">Zoeken</button></form><div id="intel-status" class="status" role="status"></div><div id="intel-results" class="cards"></div></article></section>
<section class="view" data-view-panel="sources"><div class="page-heading"><div><p class="eyebrow">Source operations</p><h2>Bronnen & catalogus</h2><p>Registreren, activeren, valideren, interval beheren en feeds laden vanuit één operatorflow.</p></div><div class="actions"><button id="bootstrap" class="button secondary">Ondersteunde bronnen registreren</button><button id="refresh-sources" class="button secondary">Vernieuwen</button></div></div><div id="source-status" class="status" role="status"></div><div id="source-cards" class="cards"></div></section>
<section class="view" data-view-panel="analytics"><div class="page-heading"><div><p class="eyebrow">Visual intelligence</p><h2>Visual analytics</h2><p>Grafana Operations en Intelligence binnen dezelfde DTMO-console, met native fallbackvisualisaties.</p></div></div><article class="surface grafana-shell"><div class="grafana-tabs" role="tablist" aria-label="Grafana dashboards"><button class="button" type="button" data-grafana-tab="operations">Operations</button><button class="button secondary" type="button" data-grafana-tab="intelligence">Intelligence</button></div><p class="muted grafana-note">Grafana blijft afzonderlijk geauthenticeerd; anonymous access is uitgeschakeld. De dashboards worden hier ingebed zodat operators de DTMO-shell niet verlaten.</p><iframe id="grafana-operations" class="grafana-frame active" title="DTMO Operations dashboard" loading="lazy" referrerpolicy="same-origin"></iframe><iframe id="grafana-intelligence" class="grafana-frame" title="DTMO Intelligence dashboard" loading="lazy" referrerpolicy="same-origin"></iframe></article><h3 class="fallback-heading">Native console summary</h3><div class="grid"><article class="surface"><h3>Severity distribution</h3><div id="severity-chart" class="chart"></div><div id="severity-table"></div></article><article class="surface"><h3>Source distribution</h3><div id="source-chart" class="chart"></div><div id="source-table"></div></article><article class="surface"><h3>Connector health</h3><div id="connector-chart" class="chart"></div><div id="connector-table"></div></article></div></section>
<section class="view" data-view-panel="administration"><div class="page-heading"><div><p class="eyebrow">Control plane</p><h2>Administration</h2><p>Operationeel bronbeheer binnen dezelfde applicatieshell; bestaande RBAC blijft server-side leidend.</p></div><button class="button secondary" data-view="sources">Open bronbeheer</button></div><div class="admin-grid"><article class="surface"><h3>Source registry</h3><p>Registratie-, activatie- en intervalstatus van alle ondersteunde bronnen.</p><div id="admin-sources" class="cards"></div></article><article class="surface"><h3>Identity context</h3><label>Subject<input id="subject" value="admin-tester"></label><label>Rollen<input id="roles" value="admin"></label><label>API key<input id="api-key" type="password"></label><button id="save-identity" class="button secondary">Identiteit toepassen</button><p class="muted">Alleen local/dev/staging testcontext; production identity blijft extern beheerd.</p></article><article class="surface"><h3>Operationele grens</h3><p>Administrators kunnen bronnen registreren, valideren, activeren en uitvoeren. Review- en externe share approval-bevoegdheden blijven gescheiden.</p></article></div></section>
<section class="view" data-view-panel="governance"><div class="page-heading"><div><p class="eyebrow">Governance</p><h2>Beslisgrenzen</h2></div></div><article class="surface"><p>Ingestie, dashboards en administration verlenen geen review- of share approval-recht. Human review en externe share approval blijven afzonderlijke bevoegdheden met separation of duties.</p></article></section>
</main></div></div>
<script>
const $=id=>document.getElementById(id),esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const ctx={subject:sessionStorage.getItem('dtmo.subject')||'admin-tester',roles:sessionStorage.getItem('dtmo.roles')||'admin',apiKey:sessionStorage.getItem('dtmo.apiKey')||''};
function headers(write=false,json=false){const h={'X-DTMO-Subject':ctx.subject,'X-DTMO-Roles':ctx.roles,'X-DTMO-API-Key':ctx.apiKey};if(write)h['X-Request-ID']=crypto.randomUUID();if(json)h['Content-Type']='application/json';return h}
async function api(url,opt={}){const r=await fetch(url,{...opt,headers:{...headers(Boolean(opt.method&&opt.method!=='GET'),Boolean(opt.body)),...(opt.headers||{})}});let b={};try{b=await r.json()}catch{}if(!r.ok)throw new Error(b.detail||b.reason||`HTTP ${r.status}`);return b}
function show(name){document.querySelectorAll('[data-view-panel]').forEach(x=>x.classList.toggle('active',x.dataset.viewPanel===name));location.hash=name}
document.addEventListener('click',e=>{const b=e.target.closest('[data-view]');if(b)show(b.dataset.view)});
function initGrafana(){const base='/grafana';const ops=$('grafana-operations'),intel=$('grafana-intelligence');if(!ops.src)ops.src=`${base}/d/dtmo-operations/dtmo-operations?orgId=1&kiosk`;if(!intel.src)intel.src=`${base}/d/dtmo-intelligence/dtmo-intelligence?orgId=1&kiosk`}
function showGrafana(name){document.querySelectorAll('.grafana-frame').forEach(frame=>frame.classList.toggle('active',frame.id===`grafana-${name}`));document.querySelectorAll('[data-grafana-tab]').forEach(button=>button.classList.toggle('secondary',button.dataset.grafanaTab!==name))}
document.addEventListener('click',e=>{const tab=e.target.closest('[data-grafana-tab]');if(tab){initGrafana();showGrafana(tab.dataset.grafanaTab)}});
function bars(target,tableTarget,obj){const entries=Object.entries(obj||{});$(target).innerHTML=entries.length?entries.map(([k,v])=>`<div style="flex:1;text-align:center"><div class="bar" style="height:${Math.max(8,Math.min(160,Number(v)*8))}px" title="${esc(k)}: ${esc(v)}"></div><div class="bar-label">${esc(k)}</div></div>`).join(''):'<p class="muted">Geen data.</p>';$(tableTarget).innerHTML=entries.length?`<table><thead><tr><th>Type</th><th>Aantal</th></tr></thead><tbody>${entries.map(([k,v])=>`<tr><td>${esc(k)}</td><td>${esc(v)}</td></tr>`).join('')}</tbody></table>`:''}
async function loadDashboard(){try{const d=await api('/api/v1/dashboards/summary');$('kpi-intel').textContent=d.total_intelligence??d.intelligence_total??0;$('kpi-new').textContent=d.new_last_24h??d.intelligence_last_24h??0;bars('severity-chart','severity-table',d.by_severity||d.severity||{});bars('source-chart','source-table',d.by_source||d.sources||{});bars('connector-chart','connector-table',d.connector_health||d.connectors||{})}catch(e){$('global-status').textContent='Dashboard: '+e.message}}
function sourceCard(c,s,r){const registered=Boolean(r),enabled=Boolean(r?.enabled),supported=c.execution_status==='supported'||c.execution_status==='supported-built-in',run=s?.manual_run_available&&enabled;const why=!supported?'Niet-operationele catalogusreferentie':!registered?'Nog niet geregistreerd':!enabled?'Geregistreerd maar uitgeschakeld':'Operationeel';return `<article class="card" data-source-card="${esc(c.id)}"><div><strong>${esc(c.name)}</strong> <span class="status-pill ${run?'good':'neutral'}">${esc(why)}</span></div><div class="source-meta"><span>${esc(c.category)}</span><span>${esc(c.reliability)}</span><span class="muted-code">${esc(c.execution_profile)}</span><span>${esc(c.execution_status)}</span></div><p class="muted-code">${esc(c.endpoint_url)}</p>${registered?`<div class="source-control"><label><input type="checkbox" data-enabled="${esc(c.id)}" ${enabled?'checked':''}> Actief</label><label>Interval <input type="number" min="60" max="86400" step="60" data-interval="${esc(c.id)}" value="${esc(r.interval_seconds)}"> sec</label><button class="button secondary" data-save="${esc(c.id)}">Opslaan</button><button class="button secondary" data-validate="${esc(c.id)}">Valideren</button>${run?`<button class="button" data-run="${esc(c.id)}" data-built="${c.execution_status==='supported-built-in'}">Feed nu laden</button>`:''}</div>`:(supported?'<div class="actions"><button class="button secondary" data-bootstrap>Registreren</button></div>':'')}<div class="diagnostic" data-result="${esc(c.id)}" role="status"></div></article>`}
async function loadSources(){try{const [catalog,status,registered]=await Promise.all([api('/api/v1/admin/sources/catalog'),api('/api/v1/source-center/status'),api('/api/v1/admin/sources')]);const sm=Object.fromEntries(status.map(x=>[x.id,x])),rm=Object.fromEntries(registered.map(x=>[x.id,x]));$('kpi-catalog').textContent=catalog.length;$('kpi-runnable').textContent=registered.filter(x=>x.enabled).length;$('source-cards').innerHTML=catalog.map(c=>sourceCard(c,sm[c.id],rm[c.id])).join('');$('admin-sources').innerHTML=registered.length?registered.map(s=>`<div class="card"><strong>${esc(s.name)}</strong><p>${s.enabled?'Actief':'Uitgeschakeld'} · interval ${esc(s.interval_seconds)} sec</p><p class="muted-code">${esc(s.id)}</p></div>`).join(''):'<p class="muted">Nog geen ondersteunde bronnen geregistreerd.</p>';$('source-status').textContent=`${catalog.length} catalogusbronnen; ${registered.length} geregistreerd; ${registered.filter(x=>x.enabled).length} actief.`}catch(e){$('source-status').textContent='Bronnen laden mislukt: '+e.message}}
async function bootstrap(){try{$('source-status').textContent='Ondersteunde bronnen registreren…';await api('/api/v1/admin/sources/catalog/bootstrap',{method:'POST'});await loadSources()}catch(e){$('source-status').textContent='Bootstrap mislukt: '+e.message}}
async function patchSource(id,body){return api(`/api/v1/admin/sources/${encodeURIComponent(id)}`,{method:'PATCH',body:JSON.stringify(body)})}
async function saveSource(id){const enabled=document.querySelector(`[data-enabled="${CSS.escape(id)}"]`)?.checked,interval=Number(document.querySelector(`[data-interval="${CSS.escape(id)}"]`)?.value);const el=document.querySelector(`[data-result="${CSS.escape(id)}"]`);try{el.textContent='Instellingen opslaan…';await patchSource(id,{enabled,interval_seconds:interval});el.textContent='Broninstellingen opgeslagen.';await loadSources()}catch(e){el.textContent='Opslaan mislukt: '+e.message}}
async function validateSource(id){const el=document.querySelector(`[data-result="${CSS.escape(id)}"]`);try{el.textContent='Validatie uitvoeren…';const d=await api(`/api/v1/admin/sources/${encodeURIComponent(id)}/validate`,{method:'POST'});el.textContent=d.valid?`Valid: ${d.execution}. ${d.note||''}`:`Ongeldig: ${d.reason||'onbekende reden'}`}catch(e){el.textContent='Validatie mislukt: '+e.message}}
async function run(id,built){const el=document.querySelector(`[data-result="${CSS.escape(id)}"]`);try{el.textContent='Feed laden…';const url=built?`/connectors/${encodeURIComponent(id)}/run`:`/api/v1/admin/sources/${encodeURIComponent(id)}/run`;const d=await api(url,{method:'POST'});el.textContent=`${d.status}: ${d.records??0} records, ${d.inserted??0} inserted, ${d.indexed??0} indexed. Publication gate: ${d.publication_gate||'human-approval-required'}`;await Promise.all([loadSources(),loadDashboard()])}catch(e){el.textContent='Run mislukt/geblokkeerd: '+e.message}}
$('source-cards').addEventListener('click',e=>{const t=e.target;const r=t.closest('[data-run]'),s=t.closest('[data-save]'),v=t.closest('[data-validate]');if(r)run(r.dataset.run,r.dataset.built==='true');else if(s)saveSource(s.dataset.save);else if(v)validateSource(v.dataset.validate);else if(t.closest('[data-bootstrap]'))bootstrap()});
$('bootstrap').addEventListener('click',bootstrap);$('refresh-sources').addEventListener('click',loadSources);$('refresh-all').addEventListener('click',()=>Promise.all([loadSources(),loadDashboard()]));
$('save-identity').addEventListener('click',()=>{ctx.subject=$('subject').value.trim();ctx.roles=$('roles').value.trim();ctx.apiKey=$('api-key').value;sessionStorage.setItem('dtmo.subject',ctx.subject);sessionStorage.setItem('dtmo.roles',ctx.roles);sessionStorage.setItem('dtmo.apiKey',ctx.apiKey);$('global-status').textContent='Identiteit bijgewerkt';loadSources();loadDashboard()});
$('intel-search').addEventListener('submit',async e=>{e.preventDefault();const q=$('intel-query').value.trim();$('intel-status').textContent='Zoeken…';try{const d=await api(`/api/v1/intelligence/search?q=${encodeURIComponent(q)}`);const rows=Array.isArray(d)?d:(d.items||d.results||[]);$('intel-results').innerHTML=rows.map(x=>`<article class="card"><strong>${esc(x.title||x.id)}</strong><p>${esc(x.summary||x.description||'')}</p></article>`).join('');$('intel-status').textContent=`${rows.length} resultaten.`}catch(err){$('intel-status').textContent='Zoeken mislukt: '+err.message}});
const initial=location.hash.slice(1);if(initial&&document.querySelector(`[data-view-panel="${CSS.escape(initial)}"]`))show(initial);$('subject').value=ctx.subject;$('roles').value=ctx.roles;$('global-status').textContent='Console actief';initGrafana();loadSources();loadDashboard();
</script></body></html>'''


@router.get("/", response_class=HTMLResponse)
def unified_console_root() -> HTMLResponse:
    return HTMLResponse(_PAGE)


@router.get("/ui/console", response_class=HTMLResponse)
def unified_console() -> HTMLResponse:
    return HTMLResponse(_PAGE)
